// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "backend/db/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx tsx ./backend/db/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
